### ISSUE TITLE
Support for statuses/lookup?

### ISSUE THREAD

**Issue by timothyrenner** [adamwynne/twitter-api#63]
Any plans for supporting [`statuses/lookup`](https://dev.twitter.com/rest/reference/get/statuses/lookup)? 
This is a handy one if you've got tweets you want to "hydrate" (as they call it).

**Comment by adamwynne** [comment]
feel free to submit a pull request and I'll include it :)

**Comment by timothyrenner** [comment]
I'd be happy to, I just wanted to see if it was a quick add first, as I'm relatively new to Clojure and don't know much about network API clients.

**Comment by chbrown** [comment]
Fixed as of [`[twitter-api "0.7.9"]`](https://clojars.org/twitter-api/versions/0.7.9) via 73d1cfd, thanks @Ortuna!
